### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by Thazz** [iralabdisco/ira_laser_tools#19]
Any plans for official melodic release? Current version compiles fine on melodic, only some minor changes would be needed to be fully compatible with PCL 1.8.

**Comment by trigal** [comment]
not at the moment, but I'll try to do something with this package next month, there are a couple of pull requests and enhancements that worth to be merged. If you can add a pull request would be nice

**Comment by marc-hanheide** [comment]
I can confirm it works fine on `melodic`. I'm even happy to run `bloom-release` but obviously I don't have push permission to https://github.com/iralabdisco/ira_laser_tools-release so would have to release to another release repo. I'd try to avoid this, but it requires you @trigal to make a release. We kind of depend on this :-) Thanks

**Comment by trigal** [comment]
@marc-hanheide today I'll talk with @pietrocolombo about this. We'll try to update everything and maybe accept some old pull requests.

@pietrocolombo can you double-check if everything is ok with the melodic release?

**Comment by marc-hanheide** [comment]
Thanks, @gpdas will be equally happy about this.

**Comment by pietrocolombo** [comment]
We made the release for melodic 😊. We are waiting for approval of the [pull request](https://github.com/ros/rosdistro/pull/23760)

**Comment by marc-hanheide** [comment]
great! Thanks a lot, folks!

**Comment by pietrocolombo** [comment]
now is available with apt install ros-melodic-ira-laser-tools
we can close the issue?
