### ISSUE TITLE
Intensity of the lasers

### ISSUE THREAD

**Issue by hs2041** [iralabdisco/ira_laser_tools#24]
Hi,
I am able to get the resultant laserscan message but the intensity of the laserscans is lost. Is there some way to get the intensity?

**Comment by pietrocolombo** [comment]
Hi,
Currently, the intensity is not implemented, but can you send us a bag with your laser data?
So I look at whether it is possible to implement it

**Comment by pietrocolombo** [comment]
Hi,
We added the intensity in the output message.
Can you let me know if branch development works with your lasers?

**Comment by hs2041** [comment]
Hi,
It's working! I just saw your message. Thanks for the help!!

**Comment by mohamedbenftima** [comment]
Hello , Why are these modifications no longer available in the ros1-master branch?
