### ISSUE TITLE
 Release for ROS noetic

### ISSUE THREAD

**Issue by Rayman** [iralabdisco/ira_laser_tools#30]
Hey everyone,

Are there plans for releasing this package to ROS noetic? After a quick search I could not find any information about this.

Thanks!

**Comment by simonbogh** [comment]
+👍 for a Noetic release. Is this in the pipeline soon?

**Comment by JackFrost67** [comment]
wip, but migration is pretty easy. idk if it is needed, but I managed to get it work, just putting `cmake_minimum_required(VERSION 3.0.2)` in CMakeLists.txt. Sorry for the delay.
