### ISSUE TITLE
Use latest timestamp in laser merger scan publish

### ISSUE THREAD

**Issue by hcostelha** [iralabdisco/ira_laser_tools#36]
Hi,

Regarding the timestamp that is published by the laser scan merger, wouldn't it be more correct to use the timestamp associated with the last sensor reading included in the merge, instead of using the current time?

The change to do so is pretty simple, since it is enough to change the "laserscan_multi_merger.cpp" file so that the function pointcloud_to_laserscan accepts an additional argument, and pass that argument on the call to that function (in scanCallback), by using the received timestamp.

I can send a pull request with the change, if this change is welcome.

**Comment by trigal** [comment]
Hi Hugo,

your idea sounds good to me but I'm not working on this project anymore, so I'd appreciate the pull-request. 

Bests,
Augusto
