### ISSUE TITLE
use of last version on noetic

### ISSUE THREAD

**Issue by davidemannone** [iralabdisco/ira_laser_tools#45]
I have a differnt behavior of your package by use of the apt get version or the source code: with the last one (building it with catkin tools) all works fine, with the installer version the same workspace didn't work anymore.

With the install version and same launch file i get this continous warning message:
TF_REPEATED_DATA ignoring data with redundant timestamp for frame odom at time 0.10000 according to authotity unknown_publisher at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp

With the compiled version i do not.

**Comment by JackFrost67** [comment]
Sorry, my regrets, I'm currently working on other stuff and following lectures at university, so no time to prepare the release. I have done the release now, time to merge it and probably sync, and then the package should be okay even with apt.

**Comment by davidemannone** [comment]
Nice, thank you!
Please notice me here when ready.

**Comment by JackFrost67** [comment]
u can update with apt

**Comment by davidemannone** [comment]
It works! 
Thank you very much.
