### ISSUE TITLE
Is this project only simple merge laser data not transform coordinate

### ISSUE THREAD

**Issue by Julius-ZCJ** [iralabdisco/ira_laser_tools#46]
Here is a question: When I use this two lasers in my test-car to nav and obstacle avoidance, I found an obstacle has become two obstacles in test-car system, then, I found this because an obstacle in two lasers is not in same area, In other words, two lasers get data is not overlap. As show in follow picture:

![Screenshot 2022-02-15 16:42:06](https://user-images.githubusercontent.com/42171296/154173504-3e649ec7-4f12-4bc3-9ae4-ec2c8f98c4df.png)

I want to use this project code to transform and merge two lasers data to solve this question, but I found the data after merge also has this problem. Is this project only simple merge data not transform coordinate?

**Comment by trigal** [comment]
Hi, if the picture is from your system before using ira_laser_tools, it means that you didn’t setup your TF transforms correctly. Ira_laser_tools just creates one laser scan message from two separate messages, it merges the data. As we wrote in our arxiv document, “_The only requirement for this node to work properly is that the roto- translations between the virtual laser scanners and the reference frame of the point cloud must be specified to TF_“. I believe you should double check your TF tree (and transform coordinates) to solve your issue, then, if needed, you can use this tool to merge multiple messages into a single one.

Bests,
Augusto
